'use server'

import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { createClient } from '../../lib/supabase/server'

export async function createPipeline(formData: FormData) {
  const supabase = await createClient()

  const {
    data: { user },
  } = await supabase.auth.getUser()

  if (!user) {
    redirect('/login')
  }

  const name = formData.get('name') as string
  const description = formData.get('description') as string

  // Insert new pipeline (pipeline_token is auto-generated by the database schema)
  const { data, error } = await supabase
    .from('pipelines')
    .insert({
      user_id: user.id,
      name,
      description,
    })
    .select('id')
    .single()

  if (error) {
    throw new Error(error.message)
  }

  revalidatePath('/dashboard')
  redirect(`/pipelines/${data.id}`)
}
export async function signout() {
  const { createClient } = await import("@/lib/supabase/server");
  const { redirect } = await import("next/navigation");
  const { revalidatePath } = await import("next/cache");
  
  const supabase = await createClient();
  await supabase.auth.signOut();
  revalidatePath("/", "layout");
  redirect("/login");
}
